%% Run_TaskC_Batch.m
% Batch run for Task C (Case 1..7)
% Requires:
%   Ident_SetDefaultUin.m, Ident_GetTFParaFromPhyPara.m
%   Ident_SimulateRun.m, Ident_FilterRun.m
%   MIC_Mdl_Inverted_Pendulum.slx, MIC_Mdl_IdentFilter.slx
% Author: (generated by ChatGPT) - modify as needed

clc; clearvars; close all;

%% ----- 0. Basic physical parameters (copy from homework) -----
PhyPara.mp = 0.127;
PhyPara.Lc=0.1685;
PhyPara.Jp=0.0012;
PhyPara.Bp=0.0024;
PhyPara.Lr=0.216;
PhyPara.Jr=0.001;
PhyPara.Br=0.0024;
PhyPara.Rm=2.6;
PhyPara.kt=7.68e-3;
PhyPara.km=7.68e-3;
PhyPara.Kg=70;
PhyPara.eta_m=0.69;
PhyPara.eta_g=0.9;
PhyPara.g=9.8;
PhyPara.AcFric = 0.4;

InitX = [0,0,6,0]; % 初始状态 [theta0,theta0_dot,alpha0,alpha0_dot]

%% ----- 1. Simulation run info & default input -----
SimuRunInfo.IdentTs = 0.002;
SimuRunInfo.TotalTime = 10;

% default UinSet (we will override if needed)
UinSetIP.WaveFlag = 1; % square by default
UinSetIP.Amp = 0.8;
UinSetIP.Fre = 0.8*2*pi;
UinSetIP.SumSinFreRange = [0.01,30];
UinSetFre = UinSetIP;
UinSetCmp = UinSetIP;

% Build NominalPara and default UinData
NominalPara = Ident_GetTFParaFromPhyPara(PhyPara);
UinData = Ident_SetDefaultUin(UinSetCmp,SimuRunInfo);

ModelSelFlag = 3; % use pendulum (nonlinear pendulum) as in your script

%% ----- 2. Task C case definitions -----
% Cases table:
% [sigma_deg, filter_wn, filter_zeta, Ad (disturb amp), fd]
cases = {
    0,  15, 0.7, 0.0, 1;
    0,   5, 0.7, 0.0, 1;
    0, 300, 0.7, 0.0, 1;
    1,  15, 0.7, 0.0, 1;
    3,  15, 0.7, 0.0, 1;
    0,  15, 0.7, 0.1, 1;
    0,  15, 0.7, 0.5, 1;
    };

Ncase = size(cases,1);

% Reserve results
Results = struct();
Results.caseName = cell(Ncase,1);
Results.Taot = nan(Ncase,1);
Results.Kt = nan(Ncase,1);
Results.Ka = nan(Ncase,1);
Results.Ac = nan(Ncase,1);
Results.Kr = nan(Ncase,1);
Results.wr = nan(Ncase,1);
Results.zeta_r = nan(Ncase,1);
Results.RMS_alpha_ddot = nan(Ncase,1);
Results.beta_table = cell(Ncase,1);
Results.beta_rod = cell(Ncase,1);

%% ----- 3. Loop over cases -----
for k = 1:Ncase
    sigma_deg = cases{k,1};
    filter_wn = cases{k,2};
    filter_zeta = cases{k,3};
    Ad = cases{k,4};
    fd = cases{k,5};
    Results.caseName{k} = sprintf('Case%d',k);
    fprintf('--- Running %s: sigma=%g deg, wf=%g, zeta=%g, Ad=%g, fd=%g ---\n', ...
        Results.caseName{k}, sigma_deg, filter_wn, filter_zeta, Ad, fd);
    
    % ----- Disturbance setup -----
    DisturbPara.Dis = [Ad, fd, 0];
    noiseTs = SimuRunInfo.IdentTs;
    % Interpret sigma_deg as degrees standard deviation -> convert to rad variance
    var_rad = (sigma_deg*pi/180)^2;
    % DisturbPara.Noise format: [mean variance seed noiseTs] for 4 channels
    DisturbPara.Noise = [0 var_rad 123 noiseTs; ...
                         0 var_rad 111 noiseTs; ...
                         0 var_rad 121 noiseTs; ...
                         0 var_rad 113 noiseTs];
                     
    % ----- Ident filter settings -----
    IdentSet.Filterwn = filter_wn;
    IdentSet.FilterZeta = filter_zeta;
    IdentSet.Difwn = 200;
    IdentSet.DifZeta = 1;
    IdentSet.Alpha1Flag = 0;
    
    % ----- regenerate UinData in case we want to change Uin later -----
    UinData = Ident_SetDefaultUin(UinSetCmp,SimuRunInfo);
    
    % ----- 3.1 simulate pendulum with current disturbance/noise -----
    IPResData = Ident_SimulateRun(NominalPara,ModelSelFlag,UinData,InitX,DisturbPara,SimuRunInfo);
    
    % ----- 3.2 filter the response (Ident_FilterRun) -----
    FilterResData = Ident_FilterRun(IPResData,IdentSet,SimuRunInfo,ModelSelFlag);
    data = FilterResData; % same name used in your earlier script
    
    % ----- 3.3 parameter estimation (LSE) -----
    % choose data window (drop initial transient)
    t = data.time;
    tstart = 1.0;
    tend = SimuRunInfo.TotalTime - 0.5;
    idx = find(t >= tstart & t <= tend);
    if isempty(idx)
        error('No data in chosen tstart/tend window. Adjust.');
    end
    
    % assemble regression signals (use filtered channels)
    uin_f = data.uin_f(idx);
    alpha_f = data.alpha_f(idx);
    alphadot_f = data.alphadot_f(idx);
    alphaddot_f = data.alphaddot_f(idx);
    theta_f = data.theta_f(idx);
    thetadot_f = data.thetadot_f(idx);
    thetaddot_f = data.thetaddot_f(idx);
    signthetadot_f = data.signthetadot_f(idx);
    
    % Table/table dynamics regression:
    % thetaddot = (Kt/tao)*u + (-1/tao)*thetadot + (-Kc/tao)*sign(thetadot) + (-Ka/tao)*alpha
    Phi1 = [uin_f, thetadot_f, signthetadot_f, alpha_f];
    y1 = thetaddot_f;
    % remove NaN/Inf
    bad = any(isnan(Phi1),2) | any(isinf(Phi1),2) | isnan(y1) | isinf(y1);
    Phi1(bad,:) = []; y1(bad) = [];
    
    if size(Phi1,1) < 10
        warning('Too few valid rows for table LSE in %s', Results.caseName{k});
    end
    
    beta1 = (Phi1' * Phi1) \ (Phi1' * y1);
    b1 = beta1(1); b2 = beta1(2); b3 = beta1(3); b4 = beta1(4);
    % recover physical parameters
    Taot_est = -1 / b2;
    Kt_est = b1 * Taot_est;
    Kc_est = - b3 * Taot_est;
    Ka_est = - b4 * Taot_est;
    
    % Rod dynamics regression:
    % alphaddot = Kr * thetaddot + (-omega_r^2) * alpha + (-2*zeta_r*omega_r) * alphadot
    Phi2 = [thetaddot_f, alpha_f, alphadot_f];
    y2 = alphaddot_f;
    bad2 = any(isnan(Phi2),2) | any(isinf(Phi2),2) | isnan(y2) | isinf(y2);
    Phi2(bad2,:) = []; y2(bad2) = [];
    if size(Phi2,1) < 10
        warning('Too few valid rows for rod LSE in %s', Results.caseName{k});
    end
    beta2 = (Phi2' * Phi2) \ (Phi2' * y2);
    Kr_est = beta2(1);
    neg_omega2 = beta2(2);
    neg_2zetaomega = beta2(3);
    if neg_omega2 < 0
        omega_r_est = sqrt(-neg_omega2);
        zeta_r_est = - neg_2zetaomega / (2 * omega_r_est);
    else
        omega_r_est = NominalPara.wr;
        zeta_r_est = NominalPara.kesair; % fallback
        warning('Estimated beta2(2) >= 0 for %s; using nominal wr/kesair as fallback', Results.caseName{k});
    end
    
    % store results
    Results.Taot(k) = Taot_est;
    Results.Kt(k) = Kt_est;
    Results.Ka(k) = Ka_est;
    Results.Ac(k) = Kc_est;
    Results.Kr(k) = Kr_est;
    Results.wr(k) = omega_r_est;
    Results.zeta_r(k) = zeta_r_est;
    Results.beta_table{k} = beta1;
    Results.beta_rod{k} = beta2;
    
    % residual RMS for alphaddot
    y2_pred = Phi2 * beta2;
    residuals_alpha = y2 - y2_pred;
    Results.RMS_alpha_ddot(k) = sqrt(mean(residuals_alpha.^2));
    
    % ----- 3.4 validation simulation using IdentifyPara -----
    IdentifyPara = NominalPara;
    IdentifyPara.Taot = Taot_est;
    IdentifyPara.Kt = Kt_est;
    IdentifyPara.Ka = Ka_est;
    IdentifyPara.Ac = Kc_est;
    IdentifyPara.Kr = Kr_est;
    IdentifyPara.wr = omega_r_est;
    IdentifyPara.kesair = zeta_r_est;
    IdentifyPara.wt = 1/IdentifyPara.Taot;
    IdentifyPara.deta_alpha = 0;
    IdentifyPara.deta_theta = 0;
    
    IPIdentVerifyData = Ident_SimulateRun(IdentifyPara,ModelSelFlag,UinData,InitX,DisturbPara,SimuRunInfo);
    
    % Save verification data in Results for possible plotting later
    Results.Verify{k}.time = IPIdentVerifyData.time;
    Results.Verify{k}.alpha = IPIdentVerifyData.alpha;
    Results.Verify{k}.theta = IPIdentVerifyData.theta;
    Results.Filtered{k} = data; % store filtered channels for later use
    
    fprintf('%s done: Taot=%.4g, Kt=%.4g, Ka=%.4g, Ac=%.4g, Kr=%.4g, wr=%.4g, zeta=%.4g, RMS_a_dd=%.4g\n', ...
        Results.caseName{k}, Taot_est, Kt_est, Ka_est, Kc_est, Kr_est, omega_r_est, zeta_r_est, Results.RMS_alpha_ddot(k));
    
end % end case loop

%% ----- 4. Summarize results in table and save -----
T = table((1:Ncase)', Results.caseName, Results.Taot, Results.Kt, Results.Ka, Results.Ac, Results.Kr, Results.wr, Results.zeta_r, Results.RMS_alpha_ddot, ...
    'VariableNames', {'CaseNo','CaseName','Taot','Kt','Ka','Ac','Kr','wr','zeta_r','RMS_alphaddot'});
disp(T);

save('TaskC_BatchResults.mat','Results','T','cases','SimuRunInfo','NominalPara');

%% ----- 5. Plot comparisons -----
figure('Name','Parameter estimates vs case','Units','normalized','Position',[0.05 0.05 0.9 0.8]);

subplot(3,2,1);
bar([Results.Taot]); grid on; title('\tau_t estimates'); xlabel('Case'); ylabel('\tau_t');

subplot(3,2,2);
bar([Results.Kt]); grid on; title('K_t estimates'); xlabel('Case'); ylabel('K_t');

subplot(3,2,3);
bar([Results.Ka]); grid on; title('K_a estimates'); xlabel('Case'); ylabel('K_a');

subplot(3,2,4);
bar([Results.Ac]); grid on; title('A_c (Coulomb) estimates'); xlabel('Case'); ylabel('A_c');

subplot(3,2,5);
bar([Results.wr]); grid on; title('\omega_r estimates'); xlabel('Case'); ylabel('\omega_r (rad/s)');

subplot(3,2,6);
bar([Results.zeta_r]); grid on; title('\zeta_r estimates'); xlabel('Case'); ylabel('\zeta_r');

% Add nominal lines
nomvals = NominalPara;
fprintf('\nNominal values: Taot=%.4g, Kt=%.4g, Ka=%.4g, Ac=%.4g, Kr=%.4g, wr=%.4g, zeta=%.4g\n', ...
    nomvals.Taot, nomvals.Kt, nomvals.Ka, nomvals.Ac, nomvals.Kr, nomvals.wr, nomvals.kesair);

%% ----- 6. Combined verification plots for all 7 cases -----
figure('Name','Verification: alpha & theta comparison (all cases)', ...
       'Units','normalized','Position',[0.03 0.03 0.9 0.9]);

for k = 1:Ncase
    % ===== alpha subplot =====
    subplot(Ncase,2,(k-1)*2+1);
    plot(Results.Filtered{k}.time, Results.Filtered{k}.alpha, 'b', 'LineWidth', 1); hold on;
    plot(Results.Verify{k}.time, Results.Verify{k}.alpha, 'r--', 'LineWidth', 1);
    grid on;
    title(sprintf('Case %d: \\alpha comparison', k));
    ylabel('\alpha (rad)');
    if k == Ncase
        xlabel('t (s)');
    end
    legend('filtered \alpha','identified model','Location','best');
    % 自动缩放 y 轴（根据该子图的数据范围）
    y_all = [Results.Filtered{k}.alpha(:); Results.Verify{k}.alpha(:)];
    ylim([min(y_all)-0.05*abs(min(y_all)), max(y_all)+0.05*abs(max(y_all))]);

    % ===== theta subplot =====
    subplot(Ncase,2,(k-1)*2+2);
    plot(Results.Filtered{k}.time, Results.Filtered{k}.theta, 'b', 'LineWidth', 1); hold on;
    plot(Results.Verify{k}.time, Results.Verify{k}.theta, 'r--', 'LineWidth', 1);
    grid on;
    title(sprintf('Case %d: \\theta comparison', k));
    ylabel('\theta (rad)');
    if k == Ncase
        xlabel('t (s)');
    end
    legend('filtered \theta','identified model','Location','best');
    y_all2 = [Results.Filtered{k}.theta(:); Results.Verify{k}.theta(:)];
    ylim([min(y_all2)-0.05*abs(min(y_all2)), max(y_all2)+0.05*abs(max(y_all2))]);
end

sgtitle('System Identification Verification — All 7 Cases','FontSize',14,'FontWeight','bold');

fprintf('\nBatch run finished. Results saved to TaskC_BatchResults.mat\n');

%%

function [TFPara] = Ident_GetTFParaFromPhyPara(PhyPara)
    mp = PhyPara.mp;
    Lc = PhyPara.Lc;
    Jp = PhyPara.Jp;
    Bp = PhyPara.Bp;
    Lr = PhyPara.Lr;
    Jeq = PhyPara.Jr;
    Beq = PhyPara.Br;
    Rm = PhyPara.Rm;
    kt = PhyPara.kt;
    km = PhyPara.km;
    Kg = PhyPara.Kg;
    yitam = PhyPara.eta_m;
    yitag = PhyPara.eta_g;
    Accg = PhyPara.g;
    Ac = PhyPara.AcFric;
    
     Jr = Jeq;
     Ip = Jp + mp*Lc^2; %A1
     It = Jr + mp*Lr^2; %B1
     Ku = yitam*yitag*kt*Kg/Rm; %B2
     Br = (yitam*yitag*kt*km*Kg^2+Beq*Rm)/Rm; %Beq;
     clear TFPara;
     TFPara = PhyPara;
     TFPara.Kt = Ku/Br;
     TFPara.Taot = It/Br;
     TFPara.Ac = Ac;
     TFPara.Ka = mp*Lr*Lc/Ku;
     TFPara.wr = sqrt(mp*Accg*Lc/Ip);
     TFPara.kesair = sqrt(Bp^2/(4*Ip*mp*Accg*Lc));
     TFPara.wt = 1/TFPara.Taot;
     TFPara.Kr = Lr/Accg;
     TFPara.deta_alpha = 0;
     TFPara.deta_theta = 0;
 end

function [UinData] = Ident_SetDefaultUin(UinSet,SimuRunInfo)
  clear UinData;
  %输入正弦信号参数
    UinData.Sin =[1,4*pi,0];%[amp,fre,bias].Amp = 1;%0-2-6;
  %输入方波信号参数 
    UinData.Square = [5,15*pi,0]; %[amp,fre,bias]
  %辨识激励信号(正弦叠加信号)的设置 
    IdentTs = SimuRunInfo.IdentTs;
    identN = 2*floor(SimuRunInfo.TotalTime/IdentTs);%10000; %系统辨识的数据个数
    Identtraj = idinput([identN 1 1],'sine',[0,1],[-1,1],[500 50 1]);
    tout = 0:IdentTs:identN*IdentTs-IdentTs;
    UinData.IdentTrajData.time = tout'; %正弦叠加的辨识激励信号
    UinData.IdentTrajData.signals.values = Identtraj;
    UinData.IdentTrajData.dimensions = 1;
   %选择波形类型  
    UinData.WaveFlag = UinSet.WaveFlag;
  switch (UinSet.WaveFlag)
      case {1} %square
          UinData.Square = [UinSet.Amp,UinSet.Fre,0];%[amp,fre,bias]
      case {2} % uinsin
          UinData.Sin = [UinSet.Amp,UinSet.Fre,0];
      case {3}  %sumsinusoidal
         SumSinFreRange = UinSet.SumSinFreRange/(0.5/IdentTs);
         SumSinAmpRange = [-UinSet.Amp,UinSet.Amp]; %辨识激励信号的范围;
         sumnumber = UinSet.SumSinFreRange(2)*7.5;
         Identtraj = idinput([identN 1 1],'sine',SumSinFreRange,SumSinAmpRange,[sumnumber 50 1]);
         tout = 0:IdentTs:identN*IdentTs-IdentTs;
         UinData.IdentTrajData.time = tout'; %正弦叠加的辨识激励信号
         UinData.IdentTrajData.signals.values = Identtraj;
         UinData.IdentTrajData.dimensions = 1;
      case {4} %custom define uin
        UinData.IdentTrajData.time = UinSet.time;%正弦叠加的辨识激励信号
        UinData.IdentTrajData.signals.values = UinSet.uin;
        UinData.IdentTrajData.dimensions = 1;
        UinData.WaveFlag = 3;
  end
end

function [SysResData]=Ident_SimulateRun(TFPara,ModelSelFlag,UinData,InitX,DisturbPara,SimuRunInfo)
 
  switch ModelSelFlag 
      case 0 %servo table without rod
       ModelSelFlagNonlin = ModelSelFlag;
       ModelSelFlagLin = ModelSelFlag;
      case {1,2} %Inverted Pendulum
       ModelSelFlagNonlin = ModelSelFlag;
       ModelSelFlagLin = 2;   
     case {3,4} %Pendulum
       ModelSelFlagNonlin = ModelSelFlag;
       ModelSelFlagLin = 4;   
 end
  assignin('base', 'WaveFlag',UinData.WaveFlag); 
  assignin('base', 'TFPara',TFPara); 
  assignin('base', 'ModelSelFlagNonlin',ModelSelFlagNonlin);
  assignin('base', 'ModelSelFlagLin',ModelSelFlagLin);
  assignin('base', 'InitX',InitX);  
  assignin('base', 'IdentTs',SimuRunInfo.IdentTs);  
  assignin('base', 'UinSquare',UinData.Square);  
  assignin('base', 'UinSin',UinData.Sin);  
  assignin('base', 'IdentTrajData',UinData.IdentTrajData);  
  assignin('base', 'UinDis',DisturbPara.Dis); 
  assignin('base', 'NoisePara',DisturbPara.Noise); 
  sim('MIC_Mdl_Inverted_Pendulum.slx',SimuRunInfo.TotalTime); %simulink 仿真
    y1 = ResponseData.signals.values;
    t1 = ResponseData.time; 
    clear SysResData;
    %记录响应数据
    SysResData.time = t1;
    SysResData.uin = y1(:,1);
    SysResData.theta = y1(:,2);
    SysResData.thetadot = y1(:,3);
    SysResData.alpha = y1(:,4);
    SysResData.alphadot = y1(:,5);
   
    SysResData.theta_Lin = y1(:,6);
    SysResData.thetadot_Lin = y1(:,7);
    SysResData.alpha_Lin = y1(:,8);
    SysResData.alphadot_Lin = y1(:,9);
end

function [FilterResData]=Ident_FilterRun(ResData,IdentSet,SimuRunInfo,ModelSelFlag)
 if(ModelSelFlag ==1)
    Alpha1Flag = 1; 
 else
    Alpha1Flag = 0;
 end
  clear OriResData;
  OriResData.time = ResData.time;
  OriResData.signals.values = [ResData.uin ResData.alpha ResData.theta ResData.alphadot  ResData.thetadot];%[u2,alpha2,theta2];
  OriResData.signals.dimensions = 5;
  assignin('base', 'OriResData',OriResData); 
  assignin('base', 'Difwn',IdentSet.Difwn); 
  assignin('base', 'DifZeta',IdentSet.DifZeta);  
  assignin('base', 'Alpha1Flag',Alpha1Flag); 
  assignin('base', 'Identwn',IdentSet.Filterwn); 
  assignin('base', 'IdentZeta',IdentSet.FilterZeta);
  assignin('base', 'IdentTs',SimuRunInfo.IdentTs);  

  sim('MIC_Mdl_IdentFilter.slx',SimuRunInfo.TotalTime); %simulink 仿真
    y1 = IdentFilterData.signals.values;
    t1 = IdentFilterData.time; 
    clear FilterResData;
    FilterResData.time = t1;
    FilterResData.uin_f = y1(:,1);
    FilterResData.alpha_f = y1(:,2);
    FilterResData.alphadot_f = y1(:,3);
    FilterResData.alphaddot_f = y1(:,4);
    FilterResData.signalphadot_f = y1(:,5);
    FilterResData.one_f = y1(:,6);
    FilterResData.theta_f = y1(:,7);
    FilterResData.thetadot_f = y1(:,8);
    FilterResData.thetaddot_f = y1(:,9);
    FilterResData.signthetadot_f = y1(:,10);
    FilterResData.uin = y1(:,11);
    FilterResData.alpha = y1(:,12);
    FilterResData.theta = y1(:,13);
    FilterResData.alphadot = y1(:,14);
    FilterResData.thetadot = y1(:,15);
end